### ISSUE TITLE
Consider PR to add sessionStorage as  a configuration to  @storeon/localstorage

### ISSUE THREAD

**Issue by ruimarques** [koddr/storeon-sessionstorage#1]
Any reason why this is a fork instead of a configuration on @storeon/localstorage ?

**Comment by koddr** [comment]
@ruimarques because I'm not `@storeon` member and can not push any configs to this repository. 

Also, naming is important — it's wrong to place sessionStorage to `@storeon/localstorage`, this is different functions. Would be great (if we're dreaming now) to create something like, `@storeon/browser-storage` and put both of this functions to it.

P.S. main of "why this is a fork ...", I need sessionStorage for my project with Storeon "right now".

**Comment by ruimarques** [comment]
Hey, just updated @storeon/localstorage to support sessionStorage, cool?

https://github.com/storeon/localstorage/pull/26
